version: '3.5'

services:

  #service 1: definition of mysql database
  myDb:
      image: muhamedkhaled/mysql_notification:5.0
      container_name: mysql-db2
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
        - MYSQL_USER=root
      ports:
        - "3307:3306"
      networks:
        - local
      restart: always

    #service 2: definition of rabbitmq
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - '5672:5672'
          # HTTP management UI
        - '15672:15672'
      networks:
        - local

    #service 3: definition of your spring-boot app
  notification:                         #it is just a name, which will be used only in this file.
      image: notification               #name of the image after dockerfile executes
      container_name: notification-app  #name of the container created from docker image
      build:
        context: ./notification             #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
          - "8084:8084"                     #docker container port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - myDb                              #dependency name (which is defined with this name 'db' in this file earlier)
        - rabbitmq
      networks:
        - local
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db2:3306/notification?allowPublicKeyRetrieval=true&useSSL=false
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_DATASOURCE_RABBITMQ_HOST=rabbitmq

    #service 4: definition of your spring-boot app
  notification-cmd:                         #it is just a name, which will be used only in this file.
      image: notification-cmd               #name of the image after dockerfile executes
      container_name: notification-cmd  #name of the container created from docker image
      build:
        context: ./notificationcmd          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8085:8085"                     #docker container port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - myDb                              #dependency name (which is defined with this name 'db' in this file earlier)
        - rabbitmq
      networks:
        - local
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db2:3306/notification?allowPublicKeyRetrieval=true&useSSL=false
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_DATASOURCE_RABBITMQ_HOST=rabbitmq



networks:
  local:
    driver: bridge