version: '3.5'

services:
  #service 1: definition of mysql database
  myDb:
      image: muhamedkhaled/mysql_notification:5.0
      container_name: mysql-db2
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
        - MYSQL_USER=root
      ports:
        - "3307:3306"
      networks:
        - local
      restart: always


    #service 3: definition of your spring-boot app
  notification:                        #it is just a name, which will be used only in this file.
      image: notification               #name of the image after dockerfile executes
      container_name: notification-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
          - "8084:8084"                       #docker containter port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - myDb                                #dependency name (which is defined with this name 'db' in this file earlier)
      networks:
        - local
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db2:3307/notification?useSSL=false
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root

networks:
  local:
    driver: bridge